/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Connection1;

/**
 *
 * @author Anis
 */
public class vehicule extends javax.swing.JFrame {

   Connection1 co= new Connection1();
    Statement st;
    ResultSet rs;
    DefaultTableModel model= new DefaultTableModel();
    public vehicule() {
         initComponents();
         icon();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setResizable(false);
      try { 
         st=co.connecterBD().createStatement();
            rs=st.executeQuery("select*from vehicule");
            // l'ajout des collonnes au modele 
            model.addColumn("matricule");
            model.addColumn("marque");
            model.addColumn("modele");
            model.addColumn("couleur");
            model.addColumn("prix");
            //model.addColumn("etat");
           
            
            // l'ajout des lignes dans le model 
            while (rs.next() ) {                
                model.addRow(new Object[]{rs.getObject("matricule"),
                    rs.getObject("marque"),
                    rs.getObject("modele"),
                    rs.getObject("couleur"),
                    rs.getObject("prix"),
                    //rs.getObject("etat"),
                    }); 
                
                
            }
            tableSt.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(vehicule.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("logo.png")));
    }
    public void actualisation(){
        model.setRowCount(0);
        model.setColumnCount(0);
        try { 
         st=co.connecterBD().createStatement();
            rs=st.executeQuery("select*from vehicule");
            // l'ajout des collonnes au modele 
            model.addColumn("matricule");
            model.addColumn("marque");
            model.addColumn("modele");
            model.addColumn("couleur");
            model.addColumn("prix");
            //model.addColumn("etat");
           
            
            // l'ajout des lignes dans le model 
            while (rs.next() ) {                
                model.addRow(new Object[]{rs.getObject("matricule"),
                    rs.getObject("marque"),
                    rs.getObject("modele"),
                    rs.getObject("couleur"),
                    rs.getObject("prix"),
                    //rs.getObject("etat"),
                    }); 
                
                
            }
            tableSt.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(vehicule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }public void affiche(int l){
        matricule.setText(tableSt.getValueAt(l, 0).toString());
        marque.setText(tableSt.getValueAt(l, 1).toString());
        modele.setText(tableSt.getValueAt(l, 2).toString());
        couleur.setText(tableSt.getValueAt(l, 3).toString());
        prix.setText(tableSt.getValueAt(l, 4).toString());
       //numtel.setText(tableSt.getValueAt(l, 5).toString());
       ;
    }
     public void viderFormulaire() {
        matricule.setText(null);
        marque.setText(null);
        modele.setText(null);
        couleur.setText(null);
        prix.setText(null);
        //numtel.setText(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        modele = new javax.swing.JTextField();
        couleur = new javax.swing.JTextField();
        marque = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        ajout = new javax.swing.JButton();
        modif = new javax.swing.JButton();
        sup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        trech = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSt = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1340, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Veuillez renseigner les cahmps suivants");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 487, 36));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Marque");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, 141, 28));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Modèle");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 217, 141, 28));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Couleur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 261, 141, 28));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Matricule");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 129, 141, 28));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("Prix");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, 141, 28));

        matricule.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        getContentPane().add(matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 134, 370, 28));

        modele.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        modele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeleActionPerformed(evt);
            }
        });
        getContentPane().add(modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 222, 370, 28));

        couleur.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        couleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleurActionPerformed(evt);
            }
        });
        getContentPane().add(couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 266, 370, 28));

        marque.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueActionPerformed(evt);
            }
        });
        getContentPane().add(marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 178, 370, 28));

        prix.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        getContentPane().add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 310, 370, 28));

        ajout.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        ajout.setForeground(new java.awt.Color(0, 153, 153));
        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/addd.png"))); // NOI18N
        ajout.setText("Ajouter");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });
        getContentPane().add(ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 170, 50));

        modif.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        modif.setForeground(new java.awt.Color(0, 153, 153));
        modif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modifier.png"))); // NOI18N
        modif.setText("Modifier");
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });
        getContentPane().add(modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 50));

        sup.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        sup.setForeground(new java.awt.Color(0, 153, 153));
        sup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/supprimer.png"))); // NOI18N
        sup.setText("Supprimer");
        sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supActionPerformed(evt);
            }
        });
        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, 50));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setText("Recherche:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        trech.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        trech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trechActionPerformed(evt);
            }
        });
        trech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                trechKeyReleased(evt);
            }
        });
        getContentPane().add(trech, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 420, 36));

        tableSt.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tableSt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableSt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 730, 290));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("Liste Véhicules");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 190, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void modeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeleActionPerformed

    private void couleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couleurActionPerformed

    private void marqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueActionPerformed

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
        try {
            st=co.connecterBD().createStatement();
            st.executeUpdate ("insert into vehicule(matricule,marque,modele,couleur,prix)values('"+
                matricule.getText()
                +"','"+ marque.getText()+"','"+
                modele.getText()+"','"+couleur.getText()+"','"+prix.getText()+"')");
            JOptionPane.showMessageDialog(this,"Ajout avec succés");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Echec de L'ajout"+ex.getMessage());
            Logger.getLogger(vehicule.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualisation();
        viderFormulaire();
    }//GEN-LAST:event_ajoutActionPerformed

    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed
        if (JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment Modifier",
            "Confirme",   JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
        try {
            st=co.connecterBD().createStatement();
            st.executeUpdate(" Update vehicule set matricule= '"+matricule.getText() +"',marque='"+marque.getText()
                + "',modele='" + modele.getText()+"' , couleur='" +couleur.getText()+"' , prix='" +prix.getText()+"' "
                    + " where matricule= '"+tableSt.getValueAt(tableSt.getSelectedRow(),0 )+ "'");
            JOptionPane.showMessageDialog(this, "Modification avec succés");
            actualisation();
            viderFormulaire();

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Echec de la modification"+ex.getMessage());
            Logger.getLogger(vehicule.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    }//GEN-LAST:event_modifActionPerformed

    private void supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supActionPerformed
        if (JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment Supprimer","Confirme",
            JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION) {
        try {
            st=co.connecterBD().createStatement();
            st.executeUpdate("Delete from vehicule where matricule= '"+
                tableSt.getValueAt(tableSt.getSelectedRow(),0) + "'");
            JOptionPane.showMessageDialog(this, "Suppression réussie");
            actualisation();
            viderFormulaire();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Echec de la suppression"+ex.getMessage());
            Logger.getLogger(vehicule.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    }//GEN-LAST:event_supActionPerformed

    private void trechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trechActionPerformed

    private void trechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_trechKeyReleased
        DefaultTableModel table =(DefaultTableModel)tableSt.getModel();
        String search=trech.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(table);
        tableSt.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_trechKeyReleased

    private void tableStMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStMouseClicked
        affiche(tableSt.getSelectedRow());
    }//GEN-LAST:event_tableStMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout;
    private javax.swing.JTextField couleur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField modele;
    private javax.swing.JButton modif;
    private javax.swing.JTextField prix;
    private javax.swing.JButton sup;
    private javax.swing.JTable tableSt;
    private javax.swing.JTextField trech;
    // End of variables declaration//GEN-END:variables
}
